name: Build FDPClient

# Triggers the workflow on push or pull request to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Defines a single build job
jobs:
  build:
    # Runs on an Ubuntu runner (free and widely used)
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 2: Set up JDK 8 (FDPClient requires Java 8)
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin' # Eclipse Temurin OpenJDK distribution

    # Step 3: Grant execute permission to Gradle wrapper (needed for Linux)
    - name: Grant Execute Permission for Gradlew
      run: chmod +x gradlew

    # Step 4: Build the project with Gradle
    - name: Build with Gradle
      run: ./gradlew build

    # Step 5: Upload the built .jar as an artifact
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: FDPClient-Build
        path: build/libs/*.jar
